In [11]:
import numpy as np

def jacobi(A, b, x0, tol, max_iterations):
    absError = []
    n = len(b)
    x = x0.copy()

    for k in range(max_iterations):
        x_new = np.zeros_like(x)

        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
            
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k

        x = x_new

    return x, max_iterations

In [12]:
import numpy as np

def gauss_seidel(A, b, x0, tol, max_iterations):
    absError = []
    
    n = len(b)
    x = x0.copy()

    for k in range(max_iterations):
        x_new = x.copy()

        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]

        

        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k

        
        x = x_new
        
        

    return x, max_iterations
    

In [13]:
##Challenge A - Copied from Homework but changes values + added time
import time 
A = np.array([
    [10, -1,  2,  0,  0],
    [-1, 11, -1,  3,  0],
    [ 2, -1, 10, -1,  0],
    [ 0,  3, -1,  8, -2],
    [ 0,  0,  0, -2,  9]
], dtype=float)


b = np.array([
    14,
    30,
    26,
    25,
    37
], dtype=float)

x0 = np.zeros_like(b)
beg = time.time()
x, max_iterations = jacobi(A, b, x0, 1e-6, 102)
end = time.time()

print("Jacobi")
print(x)

print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end - beg)
print(" ")
print("Gauss-seidel")
beg = time.time()
x, max_iterations = gauss_seidel(A, b, x0, 1e-6, 102)
end = time.time()
print(x)

print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end-beg)

Jacobi
[0.99999995 2.00000025 2.99999986 4.00000008 4.99999983]
Number of iterations: 
18
Time: 
0.0021736621856689453
 
Gauss-seidel
[1.00000003 2.00000002 2.99999999 3.99999998 5.        ]
Number of iterations: 
10
Time: 
0.0007166862487792969


In [14]:
#Challenge 7 Part 1
A = np.array([

[0.582745, 0.48 , 0.10 , 0.  , 0.  ],
[0.48 , 1.044129, 0.46 , 0.10 , 0.  ],
[0.10 , 0.46 , 1.10431 , 0.44 , 0.10 ],
[0.  , 0.10 , 0.44 , 0.963889, 0.42 ],
[0.  , 0.  , 0.10 , 0.42 , 0.522565]], dtype=float)

b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)



x0 = np.zeros_like(b)
beg = time.time()
x, max_iterations = jacobi(A, b, x0, 1e-6, 102)
end = time.time()



print("Jacobi")
print(x)
print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end - beg)
print(" ")
print("Gauss-seidel")
beg = time.time()
x, max_iterations = gauss_seidel(A, b, x0, 1e-6, 102)
end = time.time()
print(x)

print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end-beg)




Jacobi
[0.34802678 0.34768838 0.34764265 0.347823   0.34826422]
Number of iterations: 
102
Time: 
0.007017374038696289
 
Gauss-seidel
[0.99999926 1.00000045 0.99999989 0.99999997 1.00000005]
Number of iterations: 
20
Time: 
0.0016739368438720703


In [15]:
##Part 2 
#Challenge 7 Part 1
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])

x0 = np.zeros_like(b)
beg = time.time()
x, max_iterations = jacobi(A, b, x0, 1e-6, 102)
end = time.time()



print("Jacobi")
print(x)
print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end - beg)
print(" ")
print("Gauss-seidel")
beg = time.time()
x, max_iterations = gauss_seidel(A, b, x0, 1e-6, 102)
end = time.time()
print(x)

print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end-beg)




Jacobi
[1 0]
Number of iterations: 
1
Time: 
0.0006654262542724609
 
Gauss-seidel
[1 0]
Number of iterations: 
1
Time: 
0.0005221366882324219


In [16]:
## Part 3 

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])

x0 = np.zeros_like(b)
beg = time.time()
x, max_iterations = jacobi(A, b, x0, 1e-6, 102)
end = time.time()



print("Jacobi")
print(x)
print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end - beg)
print(" ")
print("Gauss-seidel")
beg = time.time()
x, max_iterations = gauss_seidel(A, b, x0, 1e-6, 102)
end = time.time()
print(x)

print("Number of iterations: ")
print(max_iterations)
print("Time: ")
print(end-beg)



Jacobi
[0.         0.00508676]
Number of iterations: 
102
Time: 
0.005455493927001953
 
Gauss-seidel
[0.98995133 0.01014765]
Number of iterations: 
102
Time: 
0.004469633102416992
