In [26]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)
    for i in range(n):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]

        x = [0] * n
        for i in range(n - 1, -1, -1):
            x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]

        return x

In [27]:
import random
A = [
    [random.randint(-20, 20), random.randint(-20, 20), random.randint(-20, 20)],
    [random.randint(-20, 20), random.randint(-20, 20), random.randint(-20, 20)],
    [random.randint(-20, 20), random.randint(-20, 20), random.randint(-20, 20)]]

b = [
    random.randint(-20, 20),
    random.randint(-20, 20),
    random.randint(-20, 20)
]

solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [0.31132686084142397, 2.0647249190938513, -1.3300970873786409]


In [28]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.array(A, dtype=float)
    for i in range(n):
        for j in range(i + 1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                
            factor = U[j, i] / U[i, i]

            L[j, i] = factor

            for k in range(i, n):
                U[j, k] -= factor * U[i, k]

    return L, U

In [35]:
A = np.array([
    [np.random.randint(-20, 21), np.random.randint(-20, 21), np.random.randint(-20, 21)],
    [np.random.randint(-20, 21), np.random.randint(-20, 21), np.random.randint(-20, 21)],
    [np.random.randint(-20, 21), np.random.randint(-20, 21), np.random.randint(-20, 21)]
])



L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)





Matrix A:
 [[ 19  18  15]
 [ -7   7  17]
 [ 14 -17   0]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.36842105  1.          0.        ]
 [ 0.73684211 -2.22007722  1.        ]]
Upper Triangular Matrix U:
 [[ 1.90000000e+01  1.80000000e+01  1.50000000e+01]
 [ 0.00000000e+00  1.36315789e+01  2.25263158e+01]
 [ 0.00000000e+00 -3.55271368e-15  3.89575290e+01]]


In [1]:
A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

L, U = lu_decomposition(A)

print("Matrix B:\n", b)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

NameError: name 'np' is not defined